name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Run Electron tests 🧪
        uses: cypress-io/github-action@v7.2.0
        with:
          start: npm start

      - name: Run Chrome tests 🧪
        uses: cypress-io/github-action@v7.2.0
        with:
          # we have already installed everything
          install: false
          start: npm start
          browser: chrome

      - name: Run Firefox tests 🧪
        uses: cypress-io/github-action@v7.2.0
        with:
          # we have already installed everything
          install: false
          start: npm start
          browser: firefox
